[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.devnet]
token_transfer_er = "sXhfCv6D62CWq86U468hGjDou6kLzehQgYUPEWqZd3U"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "NODE_OPTIONS='--import tsx' yarn run mocha --timeout 1000000 tests/**/*.ts"
